import '@/styles/normailze.css';

import type { Metadata } from 'next';

import Provider from '@/context/Provider';

export const metadata: Metadata = {
  title: 'This is Template by 32',
  description: 'Generated by 32',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
